// <auto-generated>
// ReSharper disable All

using HospitalReservationsAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Threading;
using System.Threading.Tasks;

namespace HospitalReservationsAPI
{
    public partial interface IHospitalReservationsContext : IDisposable
    {
        DbSet<AllItemsModified> AllItemsModifieds { get; set; } // AllItemsModified
        DbSet<AllLoginLog> AllLoginLogs { get; set; } // AllLoginLog
        DbSet<Appointment> Appointments { get; set; } // Appointments
        DbSet<AppointmentStatus> AppointmentStatus { get; set; } // AppointmentStatuses
        DbSet<AppointmentStatusHistory> AppointmentStatusHistories { get; set; } // AppointmentStatusHistory
        DbSet<audit_AuditLog> audit_AuditLogs { get; set; } // AuditLogs
        DbSet<Clinic> Clinics { get; set; } // Clinics
        DbSet<Department> Departments { get; set; } // Departments
        DbSet<Doctor> Doctors { get; set; } // Doctors
        DbSet<DoctorSchedule> DoctorSchedules { get; set; } // DoctorSchedules
        DbSet<LoginApplicationForm> LoginApplicationForms { get; set; } // LoginApplicationForms
        DbSet<LoginApplicationFormRight> LoginApplicationFormRights { get; set; } // LoginApplicationFormRights
        DbSet<MedicalRecord> MedicalRecords { get; set; } // MedicalRecords
        DbSet<Notification> Notifications { get; set; } // Notifications
        DbSet<Patient> Patients { get; set; } // Patients
        DbSet<Permission> Permissions { get; set; } // Permissions
        DbSet<Role> Roles { get; set; } // Roles
        DbSet<RolePermission> RolePermissions { get; set; } // RolePermissions
        DbSet<User> Users { get; set; } // Users
        DbSet<UserRole> UserRoles { get; set; } // UserRoles

        int SaveChanges();
        int SaveChanges(bool acceptAllChangesOnSuccess);
        Task<int> SaveChangesAsync(CancellationToken cancellationToken = default(CancellationToken));
        Task<int> SaveChangesAsync(bool acceptAllChangesOnSuccess, CancellationToken cancellationToken = default(CancellationToken));
        DatabaseFacade Database { get; }
        DbSet<TEntity> Set<TEntity>() where TEntity : class;
        string ToString();

        EntityEntry Add(object entity);
        EntityEntry<TEntity> Add<TEntity>(TEntity entity) where TEntity : class;
        Task AddRangeAsync(params object[] entities);
        Task AddRangeAsync(IEnumerable<object> entities, CancellationToken cancellationToken = default);
        ValueTask<EntityEntry<TEntity>> AddAsync<TEntity>(TEntity entity, CancellationToken cancellationToken = default) where TEntity : class;
        ValueTask<EntityEntry> AddAsync(object entity, CancellationToken cancellationToken = default);
        void AddRange(IEnumerable<object> entities);
        void AddRange(params object[] entities);

        EntityEntry Attach(object entity);
        EntityEntry<TEntity> Attach<TEntity>(TEntity entity) where TEntity : class;
        void AttachRange(IEnumerable<object> entities);
        void AttachRange(params object[] entities);

        EntityEntry Entry(object entity);
        EntityEntry<TEntity> Entry<TEntity>(TEntity entity) where TEntity : class;

        TEntity Find<TEntity>(params object[] keyValues) where TEntity : class;
        ValueTask<TEntity> FindAsync<TEntity>(object[] keyValues, CancellationToken cancellationToken) where TEntity : class;
        ValueTask<TEntity> FindAsync<TEntity>(params object[] keyValues) where TEntity : class;
        ValueTask<object> FindAsync(Type entityType, object[] keyValues, CancellationToken cancellationToken);
        ValueTask<object> FindAsync(Type entityType, params object[] keyValues);
        object Find(Type entityType, params object[] keyValues);

        EntityEntry Remove(object entity);
        EntityEntry<TEntity> Remove<TEntity>(TEntity entity) where TEntity : class;
        void RemoveRange(IEnumerable<object> entities);
        void RemoveRange(params object[] entities);

        EntityEntry Update(object entity);
        EntityEntry<TEntity> Update<TEntity>(TEntity entity) where TEntity : class;
        void UpdateRange(IEnumerable<object> entities);
        void UpdateRange(params object[] entities);

        IQueryable<TResult> FromExpression<TResult> (Expression<Func<IQueryable<TResult>>> expression);

        // Scalar Valued Functions
        int FnDiagramobjects(); // dbo.fn_diagramobjects
    }
}
// </auto-generated>
