// <auto-generated>
// ReSharper disable All

using HospitalReservationsAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HospitalReservationsAPI
{
    // AllItemsModified
    public partial class AllItemsModifiedConfiguration : IEntityTypeConfiguration<AllItemsModified>
    {
        public void Configure(EntityTypeBuilder<AllItemsModified> builder)
        {
            builder.HasKey(x => x.Id).HasName("PK_AllItemsModified").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("bigint").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.Category).HasColumnName(@"Category").HasColumnType("nvarchar(max)").IsRequired();
            builder.Property(x => x.Info).HasColumnName(@"Info").HasColumnType("nvarchar(max)").IsRequired();
            builder.Property(x => x.InfoAfter).HasColumnName(@"InfoAfter").HasColumnType("nvarchar(max)").IsRequired(false);
            builder.Property(x => x.ByPersonId).HasColumnName(@"ByPersonId").HasColumnType("bigint").IsRequired();
            builder.Property(x => x.ByPersonThesiId).HasColumnName(@"ByPersonThesiId").HasColumnType("bigint").IsRequired(false);
            builder.Property(x => x.ByPersonFullName).HasColumnName(@"ByPersonFullName").HasColumnType("nvarchar(max)").IsRequired(false);
            builder.Property(x => x.ByPersonIpAddress).HasColumnName(@"ByPersonIpAddress").HasColumnType("nvarchar(max)").IsRequired(false);
            builder.Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired(false);

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<AllItemsModified> builder);
    }

}
// </auto-generated>
