// <auto-generated>
// ReSharper disable All

using HospitalReservationsAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HospitalReservationsAPI
{
    // AllLoginLog
    public partial class AllLoginLogConfiguration : IEntityTypeConfiguration<AllLoginLog>
    {
        public void Configure(EntityTypeBuilder<AllLoginLog> builder)
        {
            builder.HasKey(x => x.Id).HasName("PK_AllLoginLog").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("bigint").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.PersonInfo).HasColumnName(@"PersonInfo").HasColumnType("nvarchar(max)").IsRequired();
            builder.Property(x => x.PersonId).HasColumnName(@"PersonId").HasColumnType("bigint").IsRequired();
            builder.Property(x => x.PersonThesiId).HasColumnName(@"PersonThesiId").HasColumnType("bigint").IsRequired(false);
            builder.Property(x => x.LogInDate).HasColumnName(@"LogInDate").HasColumnType("datetime").IsRequired();
            builder.Property(x => x.PersonIpAddress).HasColumnName(@"PersonIpAddress").HasColumnType("nvarchar(max)").IsRequired(false);
            builder.Property(x => x.IsSucceded).HasColumnName(@"IsSucceded").HasColumnType("bit").IsRequired(false);
            builder.Property(x => x.ErrorMessage).HasColumnName(@"ErrorMessage").HasColumnType("nvarchar(max)").IsRequired(false);

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<AllLoginLog> builder);
    }

}
// </auto-generated>
