// <auto-generated>
// ReSharper disable All

using HospitalReservationsAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HospitalReservationsAPI
{
    // AppointmentStatuses
    public partial class AppointmentStatusConfiguration : IEntityTypeConfiguration<AppointmentStatus>
    {
        public void Configure(EntityTypeBuilder<AppointmentStatus> builder)
        {
            builder.HasKey(x => x.AppointmentStatusId).HasName("PK_AppointmentStatuses").IsClustered();

            builder.Property(x => x.AppointmentStatusId).HasColumnName(@"AppointmentStatusId").HasColumnType("tinyint").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Code).HasColumnName(@"Code").HasColumnType("nvarchar(30)").IsRequired().HasMaxLength(30);
            builder.Property(x => x.Description).HasColumnName(@"Description").HasColumnType("nvarchar(100)").IsRequired(false).HasMaxLength(100);

            builder.HasIndex(x => x.Code).HasDatabaseName("UQ_AppointmentStatuses_Code").IsUnique();

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<AppointmentStatus> builder);
    }

}
// </auto-generated>
