// <auto-generated>
// ReSharper disable All

using HospitalReservationsAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HospitalReservationsAPI
{
    // Appointments
    public partial class AppointmentConfiguration : IEntityTypeConfiguration<Appointment>
    {
        public void Configure(EntityTypeBuilder<Appointment> builder)
        {
            builder.HasKey(x => x.AppointmentId).HasName("PK_Appointments").IsClustered();

            builder.Property(x => x.AppointmentId).HasColumnName(@"AppointmentId").HasColumnType("uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.ClinicId).HasColumnName(@"ClinicId").HasColumnType("uniqueidentifier").IsRequired();
            builder.Property(x => x.DepartmentId).HasColumnName(@"DepartmentId").HasColumnType("uniqueidentifier").IsRequired();
            builder.Property(x => x.DoctorId).HasColumnName(@"DoctorId").HasColumnType("uniqueidentifier").IsRequired();
            builder.Property(x => x.PatientId).HasColumnName(@"PatientId").HasColumnType("uniqueidentifier").IsRequired();
            builder.Property(x => x.ScheduledStart).HasColumnName(@"ScheduledStart").HasColumnType("datetimeoffset").IsRequired();
            builder.Property(x => x.ScheduledEnd).HasColumnName(@"ScheduledEnd").HasColumnType("datetimeoffset").IsRequired();
            builder.Property(x => x.AppointmentStatusId).HasColumnName(@"AppointmentStatusId").HasColumnType("tinyint").IsRequired();
            builder.Property(x => x.Reason).HasColumnName(@"Reason").HasColumnType("nvarchar(300)").IsRequired(false).HasMaxLength(300);
            builder.Property(x => x.CreatedByUserId).HasColumnName(@"CreatedByUserId").HasColumnType("uniqueidentifier").IsRequired();
            builder.Property(x => x.CreatedAt).HasColumnName(@"CreatedAt").HasColumnType("datetimeoffset").IsRequired();
            builder.Property(x => x.UpdatedAt).HasColumnName(@"UpdatedAt").HasColumnType("datetimeoffset").IsRequired();
            builder.Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();
            builder.Property(x => x.ReminderSentAt).HasColumnName(@"ReminderSentAt").HasColumnType("datetimeoffset").IsRequired(false);

            // Foreign keys
            builder.HasOne(a => a.AppointmentStatus).WithMany(b => b.Appointments).HasForeignKey(c => c.AppointmentStatusId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_Appointments_Status");
            builder.HasOne(a => a.Clinic).WithMany(b => b.Appointments).HasForeignKey(c => c.ClinicId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_Appointments_Clinic");
            builder.HasOne(a => a.Department).WithMany(b => b.Appointments).HasForeignKey(c => c.DepartmentId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_Appointments_Department");
            builder.HasOne(a => a.Doctor).WithMany(b => b.Appointments).HasForeignKey(c => c.DoctorId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_Appointments_Doctor");
            builder.HasOne(a => a.Patient).WithMany(b => b.Appointments).HasForeignKey(c => c.PatientId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_Appointments_Patient");
            builder.HasOne(a => a.User).WithMany(b => b.Appointments).HasForeignKey(c => c.CreatedByUserId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_Appointments_CreatedBy");

            builder.HasIndex(x => x.AppointmentStatusId).HasDatabaseName("IX_Appointments_AppointmentStatusId");
            builder.HasIndex(x => new { x.ClinicId, x.ScheduledStart }).HasDatabaseName("IX_Appointments_ClinicId_ScheduledStart");
            builder.HasIndex(x => new { x.DoctorId, x.ScheduledStart }).HasDatabaseName("IX_Appointments_DoctorId_ScheduledStart");
            builder.HasIndex(x => x.PatientId).HasDatabaseName("IX_Appointments_PatientId");

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<Appointment> builder);
    }

}
// </auto-generated>
