// <auto-generated>
// ReSharper disable All

using HospitalReservationsAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HospitalReservationsAPI
{
    // AppointmentStatusHistory
    public partial class AppointmentStatusHistoryConfiguration : IEntityTypeConfiguration<AppointmentStatusHistory>
    {
        public void Configure(EntityTypeBuilder<AppointmentStatusHistory> builder)
        {
            builder.HasKey(x => x.HistoryId).HasName("PK_AppointmentStatusHistory").IsClustered();

            builder.Property(x => x.HistoryId).HasColumnName(@"HistoryId").HasColumnType("bigint").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.AppointmentId).HasColumnName(@"AppointmentId").HasColumnType("uniqueidentifier").IsRequired();
            builder.Property(x => x.OldStatusId).HasColumnName(@"OldStatusId").HasColumnType("tinyint").IsRequired(false);
            builder.Property(x => x.NewStatusId).HasColumnName(@"NewStatusId").HasColumnType("tinyint").IsRequired();
            builder.Property(x => x.ChangedByUserId).HasColumnName(@"ChangedByUserId").HasColumnType("uniqueidentifier").IsRequired(false);
            builder.Property(x => x.ChangedAt).HasColumnName(@"ChangedAt").HasColumnType("datetimeoffset").IsRequired();
            builder.Property(x => x.Reason).HasColumnName(@"Reason").HasColumnType("nvarchar(300)").IsRequired(false).HasMaxLength(300);

            // Foreign keys
            builder.HasOne(a => a.Appointment).WithMany(b => b.AppointmentStatusHistories).HasForeignKey(c => c.AppointmentId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_AppointmentStatusHistory_Appointment");
            builder.HasOne(a => a.NewStatus).WithMany(b => b.AppointmentStatusHistories_NewStatusId).HasForeignKey(c => c.NewStatusId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_AppointmentStatusHistory_NewStatus");
            builder.HasOne(a => a.OldStatus).WithMany(b => b.AppointmentStatusHistories_OldStatusId).HasForeignKey(c => c.OldStatusId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_AppointmentStatusHistory_OldStatus");
            builder.HasOne(a => a.User).WithMany(b => b.AppointmentStatusHistories).HasForeignKey(c => c.ChangedByUserId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_AppointmentStatusHistory_ChangedBy");

            builder.HasIndex(x => x.AppointmentId).HasDatabaseName("IX_AppointmentStatusHistory_AppointmentId");

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<AppointmentStatusHistory> builder);
    }

}
// </auto-generated>
