// <auto-generated>
// ReSharper disable All

using HospitalReservationsAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HospitalReservationsAPI
{
    // AuditLogs
    public partial class audit_AuditLogConfiguration : IEntityTypeConfiguration<audit_AuditLog>
    {
        public void Configure(EntityTypeBuilder<audit_AuditLog> builder)
        {
            builder.HasKey(x => x.AuditLogId).HasName("PK_AuditLogs").IsClustered();

            builder.Property(x => x.AuditLogId).HasColumnName(@"AuditLogId").HasColumnType("bigint").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.UserId).HasColumnName(@"UserId").HasColumnType("uniqueidentifier").IsRequired(false);
            builder.Property(x => x.Role).HasColumnName(@"Role").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.Timestamp).HasColumnName(@"Timestamp").HasColumnType("datetimeoffset").IsRequired();
            builder.Property(x => x.ActionType).HasColumnName(@"ActionType").HasColumnType("nvarchar(50)").IsRequired().HasMaxLength(50);
            builder.Property(x => x.EntityType).HasColumnName(@"EntityType").HasColumnType("nvarchar(50)").IsRequired().HasMaxLength(50);
            builder.Property(x => x.EntityId).HasColumnName(@"EntityId").HasColumnType("nvarchar(100)").IsRequired(false).HasMaxLength(100);
            builder.Property(x => x.SourceIp).HasColumnName(@"SourceIp").HasColumnType("nvarchar(45)").IsRequired(false).HasMaxLength(45);
            builder.Property(x => x.UserAgent).HasColumnName(@"UserAgent").HasColumnType("nvarchar(400)").IsRequired(false).HasMaxLength(400);
            builder.Property(x => x.BeforeSnapshot).HasColumnName(@"BeforeSnapshot").HasColumnType("nvarchar(max)").IsRequired(false);
            builder.Property(x => x.AfterSnapshot).HasColumnName(@"AfterSnapshot").HasColumnType("nvarchar(max)").IsRequired(false);

            builder.HasIndex(x => new { x.EntityType, x.EntityId }).HasDatabaseName("IX_AuditLogs_EntityType_EntityId");
            builder.HasIndex(x => x.Timestamp).HasDatabaseName("IX_AuditLogs_Timestamp");
            builder.HasIndex(x => new { x.UserId, x.Timestamp }).HasDatabaseName("IX_AuditLogs_UserId_Timestamp");

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<audit_AuditLog> builder);
    }

}
// </auto-generated>
