// <auto-generated>
// ReSharper disable All

using HospitalReservationsAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HospitalReservationsAPI
{
    // Clinics
    public partial class ClinicConfiguration : IEntityTypeConfiguration<Clinic>
    {
        public void Configure(EntityTypeBuilder<Clinic> builder)
        {
            builder.HasKey(x => x.ClinicId).HasName("PK_Clinics").IsClustered();

            builder.Property(x => x.ClinicId).HasColumnName(@"ClinicId").HasColumnType("uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar(200)").IsRequired().HasMaxLength(200);
            builder.Property(x => x.Address).HasColumnName(@"Address").HasColumnType("nvarchar(300)").IsRequired(false).HasMaxLength(300);
            builder.Property(x => x.Phone).HasColumnName(@"Phone").HasColumnType("nvarchar(30)").IsRequired(false).HasMaxLength(30);
            builder.Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsRequired();
            builder.Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();
            builder.Property(x => x.CreatedAt).HasColumnName(@"CreatedAt").HasColumnType("datetimeoffset").IsRequired();
            builder.Property(x => x.UpdatedAt).HasColumnName(@"UpdatedAt").HasColumnType("datetimeoffset").IsRequired();
            builder.Property(x => x.DeletedAt).HasColumnName(@"DeletedAt").HasColumnType("datetimeoffset").IsRequired(false);
            builder.Property(x => x.ManagerUserId).HasColumnName(@"ManagerUserId").HasColumnType("uniqueidentifier").IsRequired(false);

            builder.HasOne(a => a.ManagerUser).WithMany().HasForeignKey(c => c.ManagerUserId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_Clinics_ManagerUser");

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<Clinic> builder);
    }

}
// </auto-generated>
