// <auto-generated>
// ReSharper disable All

using HospitalReservationsAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HospitalReservationsAPI
{
    // Departments
    public partial class DepartmentConfiguration : IEntityTypeConfiguration<Department>
    {
        public void Configure(EntityTypeBuilder<Department> builder)
        {
            builder.HasKey(x => x.DepartmentId).HasName("PK_Departments").IsClustered();

            builder.Property(x => x.DepartmentId).HasColumnName(@"DepartmentId").HasColumnType("uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.ClinicId).HasColumnName(@"ClinicId").HasColumnType("uniqueidentifier").IsRequired();
            builder.Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar(150)").IsRequired().HasMaxLength(150);
            builder.Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsRequired();
            builder.Property(x => x.CreatedAt).HasColumnName(@"CreatedAt").HasColumnType("datetimeoffset").IsRequired();

            // Foreign keys
            builder.HasOne(a => a.Clinic).WithMany(b => b.Departments).HasForeignKey(c => c.ClinicId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_Departments_Clinic");

            builder.HasIndex(x => x.ClinicId).HasDatabaseName("IX_Departments_ClinicId");
            builder.HasIndex(x => new { x.ClinicId, x.Name }).HasDatabaseName("UQ_Departments_Clinic_Name").IsUnique();

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<Department> builder);
    }

}
// </auto-generated>
