// <auto-generated>
// ReSharper disable All

using HospitalReservationsAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HospitalReservationsAPI
{
    // Doctors
    public partial class DoctorConfiguration : IEntityTypeConfiguration<Doctor>
    {
        public void Configure(EntityTypeBuilder<Doctor> builder)
        {
            builder.HasKey(x => x.DoctorId).HasName("PK_Doctors").IsClustered();

            builder.Property(x => x.DoctorId).HasColumnName(@"DoctorId").HasColumnType("uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.UserId).HasColumnName(@"UserId").HasColumnType("uniqueidentifier").IsRequired();
            builder.Property(x => x.ClinicId).HasColumnName(@"ClinicId").HasColumnType("uniqueidentifier").IsRequired();
            builder.Property(x => x.DepartmentId).HasColumnName(@"DepartmentId").HasColumnType("uniqueidentifier").IsRequired();
            builder.Property(x => x.Amka).HasColumnName(@"AMKA").HasColumnType("char(11)").IsRequired(false).IsFixedLength().IsUnicode(false).HasMaxLength(11);
            builder.Property(x => x.Specialty).HasColumnName(@"Specialty").HasColumnType("nvarchar(150)").IsRequired().HasMaxLength(150);
            builder.Property(x => x.LicenseNumber).HasColumnName(@"LicenseNumber").HasColumnType("nvarchar(50)").IsRequired().HasMaxLength(50);
            builder.Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsRequired();
            builder.Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();
            builder.Property(x => x.CreatedAt).HasColumnName(@"CreatedAt").HasColumnType("datetimeoffset").IsRequired();
            builder.Property(x => x.UpdatedAt).HasColumnName(@"UpdatedAt").HasColumnType("datetimeoffset").IsRequired();
            builder.Property(x => x.DeletedAt).HasColumnName(@"DeletedAt").HasColumnType("datetimeoffset").IsRequired(false);

            // Foreign keys
            builder.HasOne(a => a.Clinic).WithMany(b => b.Doctors).HasForeignKey(c => c.ClinicId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_Doctors_Clinic");
            builder.HasOne(a => a.Department).WithMany(b => b.Doctors).HasForeignKey(c => c.DepartmentId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_Doctors_Department");
            builder.HasOne(a => a.User).WithOne(b => b.Doctor).HasForeignKey<Doctor>(c => c.UserId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_Doctors_User");

            builder.HasIndex(x => x.ClinicId).HasDatabaseName("IX_Doctors_ClinicId");
            builder.HasIndex(x => x.DepartmentId).HasDatabaseName("IX_Doctors_DepartmentId");
            builder.HasIndex(x => x.LicenseNumber).HasDatabaseName("UQ_Doctors_LicenseNumber").IsUnique();
            builder.HasIndex(x => x.UserId).HasDatabaseName("UQ_Doctors_User").IsUnique();
            builder.HasIndex(x => x.Amka).HasDatabaseName("UQ_Doctors_AMKA").IsUnique().HasFilter("[AMKA] IS NOT NULL");

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<Doctor> builder);
    }

}
// </auto-generated>
