// <auto-generated>
// ReSharper disable All

using HospitalReservationsAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HospitalReservationsAPI
{
    // DoctorSchedules
    public partial class DoctorScheduleConfiguration : IEntityTypeConfiguration<DoctorSchedule>
    {
        public void Configure(EntityTypeBuilder<DoctorSchedule> builder)
        {
            builder.HasKey(x => x.ScheduleId).HasName("PK_DoctorSchedules").IsClustered();

            builder.Property(x => x.ScheduleId).HasColumnName(@"ScheduleId").HasColumnType("uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.DoctorId).HasColumnName(@"DoctorId").HasColumnType("uniqueidentifier").IsRequired();
            builder.Property(x => x.ClinicId).HasColumnName(@"ClinicId").HasColumnType("uniqueidentifier").IsRequired();
            builder.Property(x => x.DayOfWeek).HasColumnName(@"DayOfWeek").HasColumnType("tinyint").IsRequired();
            builder.Property(x => x.StartTime).HasColumnName(@"StartTime").HasColumnType("time").IsRequired();
            builder.Property(x => x.EndTime).HasColumnName(@"EndTime").HasColumnType("time").IsRequired();
            builder.Property(x => x.SlotMinutes).HasColumnName(@"SlotMinutes").HasColumnType("int").IsRequired();
            builder.Property(x => x.EffectiveFrom).HasColumnName(@"EffectiveFrom").HasColumnType("date").IsRequired();
            builder.Property(x => x.EffectiveTo).HasColumnName(@"EffectiveTo").HasColumnType("date").IsRequired(false);
            builder.Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsRequired();
            builder.Property(x => x.CreatedAt).HasColumnName(@"CreatedAt").HasColumnType("datetimeoffset").IsRequired();

            // Foreign keys
            builder.HasOne(a => a.Clinic).WithMany(b => b.DoctorSchedules).HasForeignKey(c => c.ClinicId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_DoctorSchedules_Clinic");
            builder.HasOne(a => a.Doctor).WithMany(b => b.DoctorSchedules).HasForeignKey(c => c.DoctorId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_DoctorSchedules_Doctor");

            builder.HasIndex(x => x.DoctorId).HasDatabaseName("IX_DoctorSchedules_DoctorId");
            builder.HasIndex(x => new { x.DoctorId, x.DayOfWeek, x.StartTime, x.EffectiveFrom }).HasDatabaseName("UQ_DoctorSchedules_Shift").IsUnique();

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<DoctorSchedule> builder);
    }

}
// </auto-generated>
