// <auto-generated>
// ReSharper disable All

using HospitalReservationsAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HospitalReservationsAPI
{
    // LoginApplicationFormRights
    public partial class LoginApplicationFormRightConfiguration : IEntityTypeConfiguration<LoginApplicationFormRight>
    {
        public void Configure(EntityTypeBuilder<LoginApplicationFormRight> builder)
        {
            builder.HasKey(x => x.Id).HasName("PK_LoginApplicationFormRights").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("bigint").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.ApplicationFormId).HasColumnName(@"ApplicationFormId").HasColumnType("bigint").IsRequired();
            builder.Property(x => x.RoleId).HasColumnName(@"RoleId").HasColumnType("int").IsRequired();
            builder.Property(x => x.CanEdit).HasColumnName(@"CanEdit").HasColumnType("bit").IsRequired(false);

            builder.HasIndex(x => new { x.ApplicationFormId, x.RoleId }).HasDatabaseName("UQ_LoginApplicationFormRights_Form_Role").IsUnique();

            // Foreign keys
            builder.HasOne(a => a.Role).WithMany().HasForeignKey(c => c.RoleId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_LoginApplicationFormRights_Roles");
            builder.HasOne(a => a.LoginApplicationForm).WithMany(b => b.LoginApplicationFormRights).HasForeignKey(c => c.ApplicationFormId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_LoginApplicationFormRights_LoginApplicationForms");

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<LoginApplicationFormRight> builder);
    }

}
// </auto-generated>
