// <auto-generated>
// ReSharper disable All

using HospitalReservationsAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HospitalReservationsAPI
{
    // LoginApplicationForms
    public partial class LoginApplicationFormConfiguration : IEntityTypeConfiguration<LoginApplicationForm>
    {
        public void Configure(EntityTypeBuilder<LoginApplicationForm> builder)
        {
            builder.HasKey(x => x.Id).HasName("PK_LoginApplicationForms").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("bigint").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.ParentId).HasColumnName(@"ParentId").HasColumnType("bigint").IsRequired(false);
            builder.Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar(max)").IsRequired(false);
            builder.Property(x => x.RouteElement).HasColumnName(@"RouteElement").HasColumnType("nvarchar(max)").IsRequired(false);
            builder.Property(x => x.RouteCombPath).HasColumnName(@"RouteCombPath").HasColumnType("nvarchar(max)").IsRequired(false);
            builder.Property(x => x.NavUrl).HasColumnName(@"NavUrl").HasColumnType("nvarchar(max)").IsRequired(false);
            builder.Property(x => x.NavTitle).HasColumnName(@"NavTitle").HasColumnType("nvarchar(max)").IsRequired(false);
            builder.Property(x => x.NavIcon).HasColumnName(@"NavIcon").HasColumnType("nvarchar(max)").IsRequired(false);
            builder.Property(x => x.NavFontIcon).HasColumnName(@"NavFontIcon").HasColumnType("nvarchar(max)").IsRequired(false);
            builder.Property(x => x.NavHasBullet).HasColumnName(@"NavHasBullet").HasColumnType("bit").IsRequired(false);
            builder.Property(x => x.NavHasChildren).HasColumnName(@"NavHasChildren").HasColumnType("bit").IsRequired(false);
            builder.Property(x => x.CanEdit).HasColumnName(@"CanEdit").HasColumnType("bit").IsRequired(false);
            builder.Property(x => x.Visible).HasColumnName(@"Visible").HasColumnType("bit").IsRequired(false);
            builder.Property(x => x.DevVisible).HasColumnName(@"DevVisible").HasColumnType("bit").IsRequired(false);
            builder.Property(x => x.OrderValue).HasColumnName(@"OrderValue").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.OnlyRoute).HasColumnName(@"OnlyRoute").HasColumnType("bit").IsRequired(false);
            builder.Property(x => x.IsExternalLink).HasColumnName(@"IsExternalLink").HasColumnType("bit").IsRequired(false);
            builder.Property(x => x.IsForAllUser).HasColumnName(@"IsForAllUser").HasColumnType("bit").IsRequired();

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<LoginApplicationForm> builder);
    }

}
// </auto-generated>
