// <auto-generated>
// ReSharper disable All

using HospitalReservationsAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HospitalReservationsAPI
{
    // MedicalRecords
    public partial class MedicalRecordConfiguration : IEntityTypeConfiguration<MedicalRecord>
    {
        public void Configure(EntityTypeBuilder<MedicalRecord> builder)
        {
            builder.HasKey(x => x.RecordId).HasName("PK_MedicalRecords").IsClustered();

            builder.Property(x => x.RecordId).HasColumnName(@"RecordId").HasColumnType("uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.PatientId).HasColumnName(@"PatientId").HasColumnType("uniqueidentifier").IsRequired();
            builder.Property(x => x.AppointmentId).HasColumnName(@"AppointmentId").HasColumnType("uniqueidentifier").IsRequired(false);
            builder.Property(x => x.DoctorId).HasColumnName(@"DoctorId").HasColumnType("uniqueidentifier").IsRequired();
            builder.Property(x => x.Notes).HasColumnName(@"Notes").HasColumnType("nvarchar(max)").IsRequired();
            builder.Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();
            builder.Property(x => x.CreatedAt).HasColumnName(@"CreatedAt").HasColumnType("datetimeoffset").IsRequired();
            builder.Property(x => x.UpdatedAt).HasColumnName(@"UpdatedAt").HasColumnType("datetimeoffset").IsRequired();
            builder.Property(x => x.DeletedAt).HasColumnName(@"DeletedAt").HasColumnType("datetimeoffset").IsRequired(false);

            // Foreign keys
            builder.HasOne(a => a.Appointment).WithMany(b => b.MedicalRecords).HasForeignKey(c => c.AppointmentId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_MedicalRecords_Appointment");
            builder.HasOne(a => a.Doctor).WithMany(b => b.MedicalRecords).HasForeignKey(c => c.DoctorId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_MedicalRecords_Doctor");
            builder.HasOne(a => a.Patient).WithMany(b => b.MedicalRecords).HasForeignKey(c => c.PatientId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_MedicalRecords_Patient");

            builder.HasIndex(x => x.PatientId).HasDatabaseName("IX_MedicalRecords_PatientId");

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<MedicalRecord> builder);
    }

}
// </auto-generated>
