// <auto-generated>
// ReSharper disable All

using HospitalReservationsAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HospitalReservationsAPI
{
    // Notifications
    public partial class NotificationConfiguration : IEntityTypeConfiguration<Notification>
    {
        public void Configure(EntityTypeBuilder<Notification> builder)
        {
            builder.HasKey(x => x.NotificationId).HasName("PK_Notifications").IsClustered();

            builder.Property(x => x.NotificationId).HasColumnName(@"NotificationId").HasColumnType("uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.UserId).HasColumnName(@"UserId").HasColumnType("uniqueidentifier").IsRequired();
            builder.Property(x => x.Type).HasColumnName(@"Type").HasColumnType("nvarchar(50)").IsRequired().HasMaxLength(50);
            builder.Property(x => x.Payload).HasColumnName(@"Payload").HasColumnType("nvarchar(max)").IsRequired(false);
            builder.Property(x => x.IsRead).HasColumnName(@"IsRead").HasColumnType("bit").IsRequired();
            builder.Property(x => x.CreatedAt).HasColumnName(@"CreatedAt").HasColumnType("datetimeoffset").IsRequired();
            builder.Property(x => x.ReadAt).HasColumnName(@"ReadAt").HasColumnType("datetimeoffset").IsRequired(false);

            // Foreign keys
            builder.HasOne(a => a.User).WithMany(b => b.Notifications).HasForeignKey(c => c.UserId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_Notifications_User");

            builder.HasIndex(x => new { x.UserId, x.IsRead }).HasDatabaseName("IX_Notifications_UserId_IsRead");

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<Notification> builder);
    }

}
// </auto-generated>
