// <auto-generated>
// ReSharper disable All

using HospitalReservationsAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HospitalReservationsAPI
{
    // Patients
    public partial class PatientConfiguration : IEntityTypeConfiguration<Patient>
    {
        public void Configure(EntityTypeBuilder<Patient> builder)
        {
            builder.HasKey(x => x.PatientId).HasName("PK_Patients").IsClustered();

            builder.Property(x => x.PatientId).HasColumnName(@"PatientId").HasColumnType("uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.UserId).HasColumnName(@"UserId").HasColumnType("uniqueidentifier").IsRequired(false);
            builder.Property(x => x.FirstName).HasColumnName(@"FirstName").HasColumnType("nvarchar(100)").IsRequired().HasMaxLength(100);
            builder.Property(x => x.LastName).HasColumnName(@"LastName").HasColumnType("nvarchar(100)").IsRequired().HasMaxLength(100);
            builder.Property(x => x.Amka).HasColumnName(@"AMKA").HasColumnType("char(11)").IsRequired(false).IsFixedLength().IsUnicode(false).HasMaxLength(11);
            builder.Property(x => x.DateOfBirth).HasColumnName(@"DateOfBirth").HasColumnType("date").IsRequired();
            builder.Property(x => x.Phone).HasColumnName(@"Phone").HasColumnType("nvarchar(30)").IsRequired(false).HasMaxLength(30);
            builder.Property(x => x.Email).HasColumnName(@"Email").HasColumnType("nvarchar(256)").IsRequired(false).HasMaxLength(256);
            builder.Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();
            builder.Property(x => x.CreatedAt).HasColumnName(@"CreatedAt").HasColumnType("datetimeoffset").IsRequired();
            builder.Property(x => x.UpdatedAt).HasColumnName(@"UpdatedAt").HasColumnType("datetimeoffset").IsRequired();
            builder.Property(x => x.DeletedAt).HasColumnName(@"DeletedAt").HasColumnType("datetimeoffset").IsRequired(false);

            // Foreign keys
            builder.HasOne(a => a.User).WithOne(b => b.Patient).HasForeignKey<Patient>(c => c.UserId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_Patients_User");

            // Filtered: a plain unique index only allows one NULL total in SQL
            // Server, and most patients have neither a linked User nor an AMKA.
            builder.HasIndex(x => x.Amka).HasDatabaseName("UQ_Patients_AMKA").IsUnique().HasFilter("[AMKA] IS NOT NULL");
            builder.HasIndex(x => x.UserId).HasDatabaseName("UQ_Patients_User").IsUnique().HasFilter("[UserId] IS NOT NULL");

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<Patient> builder);
    }

}
// </auto-generated>
