// <auto-generated>
// ReSharper disable All

using HospitalReservationsAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HospitalReservationsAPI
{
    // RolePermissions
    public partial class RolePermissionConfiguration : IEntityTypeConfiguration<RolePermission>
    {
        public void Configure(EntityTypeBuilder<RolePermission> builder)
        {
            builder.HasKey(x => new { x.RoleId, x.PermissionId }).HasName("PK_RolePermissions").IsClustered();

            builder.Property(x => x.RoleId).HasColumnName(@"RoleId").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.PermissionId).HasColumnName(@"PermissionId").HasColumnType("int").IsRequired().ValueGeneratedNever();

            // Foreign keys
            builder.HasOne(a => a.Permission).WithMany(b => b.RolePermissions).HasForeignKey(c => c.PermissionId).HasConstraintName("FK_RolePermissions_Permission");
            builder.HasOne(a => a.Role).WithMany(b => b.RolePermissions).HasForeignKey(c => c.RoleId).HasConstraintName("FK_RolePermissions_Role");

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<RolePermission> builder);
    }

}
// </auto-generated>
