// <auto-generated>
// ReSharper disable All

using HospitalReservationsAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HospitalReservationsAPI
{
    // UserRoles
    public partial class UserRoleConfiguration : IEntityTypeConfiguration<UserRole>
    {
        public void Configure(EntityTypeBuilder<UserRole> builder)
        {
            builder.HasKey(x => new { x.UserId, x.RoleId }).HasName("PK_UserRoles").IsClustered();

            builder.Property(x => x.UserId).HasColumnName(@"UserId").HasColumnType("uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.RoleId).HasColumnName(@"RoleId").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.AssignedAt).HasColumnName(@"AssignedAt").HasColumnType("datetimeoffset").IsRequired();
            builder.Property(x => x.AssignedByUserId).HasColumnName(@"AssignedByUserId").HasColumnType("uniqueidentifier").IsRequired(false);

            // Foreign keys
            builder.HasOne(a => a.AssignedByUser).WithMany(b => b.UserRoles_AssignedByUserId).HasForeignKey(c => c.AssignedByUserId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_UserRoles_AssignedBy");
            builder.HasOne(a => a.Role).WithMany(b => b.UserRoles).HasForeignKey(c => c.RoleId).HasConstraintName("FK_UserRoles_Role");
            builder.HasOne(a => a.User_UserId).WithMany(b => b.UserRoles_UserId).HasForeignKey(c => c.UserId).HasConstraintName("FK_UserRoles_User");

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<UserRole> builder);
    }

}
// </auto-generated>
