// <auto-generated>
// ReSharper disable All

using HospitalReservationsAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HospitalReservationsAPI
{
    public partial class HospitalReservationsContextFactory : IDesignTimeDbContextFactory<HospitalReservationsContext>
    {
        private readonly DbContextOptions<HospitalReservationsContext> Options;

        public HospitalReservationsContextFactory()
        {
        }

        public HospitalReservationsContextFactory(DbContextOptions<HospitalReservationsContext> options)
        {
            Options = options;
        }

        public HospitalReservationsContext CreateDbContext(string[] args)
        {
            return new HospitalReservationsContext();
        }

        public HospitalReservationsContext CreateDbContext()
        {
            return new HospitalReservationsContext(Options);
        }

        public HospitalReservationsContext CreateDbContext(DbContextOptions<HospitalReservationsContext> options)
        {
            return options == null
                ? new HospitalReservationsContext()
                : new HospitalReservationsContext(options);
        }
    }
}
// </auto-generated>
