// <auto-generated>
// ReSharper disable All

using HospitalReservationsAPI;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data;
using System.Data.SqlTypes;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace HospitalReservationsAPI
{
    public partial class HospitalReservationsContext : DbContext, IHospitalReservationsContext
    {
        public HospitalReservationsContext()
        {
            InitializePartial();
        }

        public HospitalReservationsContext(DbContextOptions<HospitalReservationsContext> options)
            : base(options)
        {
            InitializePartial();
        }

        public DbSet<AllItemsModified> AllItemsModifieds { get; set; } // AllItemsModified
        public DbSet<AllLoginLog> AllLoginLogs { get; set; } // AllLoginLog
        public DbSet<Appointment> Appointments { get; set; } // Appointments
        public DbSet<AppointmentStatus> AppointmentStatus { get; set; } // AppointmentStatuses
        public DbSet<AppointmentStatusHistory> AppointmentStatusHistories { get; set; } // AppointmentStatusHistory
        public DbSet<audit_AuditLog> audit_AuditLogs { get; set; } // AuditLogs
        public DbSet<Clinic> Clinics { get; set; } // Clinics
        public DbSet<Department> Departments { get; set; } // Departments
        public DbSet<Doctor> Doctors { get; set; } // Doctors
        public DbSet<DoctorSchedule> DoctorSchedules { get; set; } // DoctorSchedules
        public DbSet<LoginApplicationForm> LoginApplicationForms { get; set; } // LoginApplicationForms
        public DbSet<LoginApplicationFormRight> LoginApplicationFormRights { get; set; } // LoginApplicationFormRights
        public DbSet<MedicalRecord> MedicalRecords { get; set; } // MedicalRecords
        public DbSet<Notification> Notifications { get; set; } // Notifications
        public DbSet<Patient> Patients { get; set; } // Patients
        public DbSet<Permission> Permissions { get; set; } // Permissions
        public DbSet<Role> Roles { get; set; } // Roles
        public DbSet<RolePermission> RolePermissions { get; set; } // RolePermissions
        public DbSet<User> Users { get; set; } // Users
        public DbSet<UserRole> UserRoles { get; set; } // UserRoles

        // The real connection string lives outside source control now — set via
        // Program.cs's AddDbContext (which reads ConnectionStrings:HospitalReservations
        // from configuration/user-secrets). A parameterless `new HospitalReservationsContext()`
        // (design-time tooling, tests) never has that, so it fails loudly here
        // instead of silently falling back to a committed credential.
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                throw new InvalidOperationException(
                    "No DbContext options configured. Register the connection string via " +
                    "ConnectionStrings:HospitalReservations (appsettings/user-secrets) instead of hardcoding it here.");
            }
        }

        public bool IsSqlParameterNull(SqlParameter param)
        {
            var sqlValue = param.SqlValue;
            var nullableValue = sqlValue as INullable;
            if (nullableValue != null)
                return nullableValue.IsNull;
            return (sqlValue == null || sqlValue == DBNull.Value);
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.ApplyConfiguration(new AllItemsModifiedConfiguration());
            modelBuilder.ApplyConfiguration(new AllLoginLogConfiguration());
            modelBuilder.ApplyConfiguration(new AppointmentConfiguration());
            modelBuilder.ApplyConfiguration(new AppointmentStatusConfiguration());
            modelBuilder.ApplyConfiguration(new AppointmentStatusHistoryConfiguration());
            modelBuilder.ApplyConfiguration(new audit_AuditLogConfiguration());
            modelBuilder.ApplyConfiguration(new ClinicConfiguration());
            modelBuilder.ApplyConfiguration(new DepartmentConfiguration());
            modelBuilder.ApplyConfiguration(new DoctorConfiguration());
            modelBuilder.ApplyConfiguration(new DoctorScheduleConfiguration());
            modelBuilder.ApplyConfiguration(new LoginApplicationFormConfiguration());
            modelBuilder.ApplyConfiguration(new LoginApplicationFormRightConfiguration());
            modelBuilder.ApplyConfiguration(new MedicalRecordConfiguration());
            modelBuilder.ApplyConfiguration(new NotificationConfiguration());
            modelBuilder.ApplyConfiguration(new PatientConfiguration());
            modelBuilder.ApplyConfiguration(new PermissionConfiguration());
            modelBuilder.ApplyConfiguration(new RoleConfiguration());
            modelBuilder.ApplyConfiguration(new RolePermissionConfiguration());
            modelBuilder.ApplyConfiguration(new UserConfiguration());
            modelBuilder.ApplyConfiguration(new UserRoleConfiguration());

            modelBuilder.Entity<Appointment>().ToTable(tb => tb.HasTrigger("trg_Appointments_StatusHistory"));

            OnModelCreatingPartial(modelBuilder);
        }


        partial void InitializePartial();
        partial void DisposePartial(bool disposing);
        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
        static partial void OnCreateModelPartial(ModelBuilder modelBuilder, string schema);

        // Scalar Valued Functions

        [DbFunction("fn_diagramobjects", "dbo")]
        public int FnDiagramobjects()
        {
            throw new Exception("Don't call this directly. Use LINQ to call the scalar valued function as part of your query");
        }
    }
}
// </auto-generated>
