// <auto-generated>
// ReSharper disable All

using HospitalReservationsAPI;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Threading;
using System.Threading.Tasks;

namespace HospitalReservationsAPI
{
    // The table 'AllActionLog' is not usable by entity framework because it
    // does not have a primary key. It is listed here for completeness.
    // AllActionLog
    [Table("AllActionLog", Schema = "dbo")]
    public partial class AllActionLog
    {
        [Display(Name = "Id")]
        public long? Id { get; set; } // Id

        [Display(Name = "Person ID")]
        public long? PersonId { get; set; } // PersonId

        [Display(Name = "Person thesi ID")]
        public long? PersonThesiId { get; set; } // PersonThesiId

        [MaxLength(200)]
        [StringLength(200)]
        [Display(Name = "Person full name")]
        public string PersonFullName { get; set; } // PersonFullName (length: 200)

        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Person ip address")]
        public string PersonIpAddress { get; set; } // PersonIpAddress (length: 50)

        [Display(Name = "Action date")]
        public DateTime? ActionDate { get; set; } // ActionDate

        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Action")]
        public string Action { get; set; } // Action (length: 100)

        [MaxLength(200)]
        [StringLength(200)]
        [Display(Name = "Target type")]
        public string TargetType { get; set; } // TargetType (length: 200)

        [Display(Name = "Target ID")]
        public long? TargetId { get; set; } // TargetId

        [Display(Name = "Details")]
        public string Details { get; set; } // Details

        [MaxLength(64)]
        [StringLength(64)]
        [Display(Name = "Correlation ID")]
        public string CorrelationId { get; set; } // CorrelationId (length: 64)

        public AllActionLog()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
