// <auto-generated>
// ReSharper disable All

using HospitalReservationsAPI;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Threading;
using System.Threading.Tasks;

namespace HospitalReservationsAPI
{
    // AllItemsModified
    [Table("AllItemsModified", Schema = "dbo")]
    public partial class AllItemsModified
    {
        [Key, Column(Order = 1)]
        [Required]
        [Display(Name = "Id")]
        public long Id { get; set; } // Id (Primary key)

        [Required(AllowEmptyStrings = true)]
        [Display(Name = "Category")]
        public string Category { get; set; } // Category

        [Required(AllowEmptyStrings = true)]
        [Display(Name = "Info")]
        public string Info { get; set; } // Info

        [Display(Name = "Info after")]
        public string InfoAfter { get; set; } // InfoAfter

        [Required]
        [Display(Name = "By person ID")]
        public long ByPersonId { get; set; } // ByPersonId

        [Display(Name = "By person thesi ID")]
        public long? ByPersonThesiId { get; set; } // ByPersonThesiId

        [Display(Name = "By person full name")]
        public string ByPersonFullName { get; set; } // ByPersonFullName

        [Display(Name = "By person ip address")]
        public string ByPersonIpAddress { get; set; } // ByPersonIpAddress

        [Display(Name = "Modified date")]
        public DateTime? ModifiedDate { get; set; } // ModifiedDate

        public AllItemsModified()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
