// <auto-generated>
// ReSharper disable All

using HospitalReservationsAPI;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Threading;
using System.Threading.Tasks;

namespace HospitalReservationsAPI
{
    // AllLoginLog
    [Table("AllLoginLog", Schema = "dbo")]
    public partial class AllLoginLog
    {
        [Key, Column(Order = 1)]
        [Required]
        [Display(Name = "Id")]
        public long Id { get; set; } // Id (Primary key)

        [Required(AllowEmptyStrings = true)]
        [Display(Name = "Person info")]
        public string PersonInfo { get; set; } // PersonInfo

        [Required]
        [Display(Name = "Person ID")]
        public long PersonId { get; set; } // PersonId

        [Display(Name = "Person thesi ID")]
        public long? PersonThesiId { get; set; } // PersonThesiId

        [Required]
        [Display(Name = "Log in date")]
        public DateTime LogInDate { get; set; } // LogInDate

        [Display(Name = "Person ip address")]
        public string PersonIpAddress { get; set; } // PersonIpAddress

        [Display(Name = "Is succeded")]
        public bool? IsSucceded { get; set; } // IsSucceded

        [Display(Name = "Error message")]
        public string ErrorMessage { get; set; } // ErrorMessage

        public AllLoginLog()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
