// <auto-generated>
// ReSharper disable All

using HospitalReservationsAPI;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Threading;
using System.Threading.Tasks;

namespace HospitalReservationsAPI
{
    // Appointments
    [Table("Appointments", Schema = "dbo")]
    public partial class Appointment
    {
        [Key, Column(Order = 1)]
        [Required]
        [Display(Name = "Appointment ID")]
        public Guid AppointmentId { get; set; } // AppointmentId (Primary key)

        [Required]
        [Display(Name = "Clinic ID")]
        public Guid ClinicId { get; set; } // ClinicId

        [Required]
        [Display(Name = "Department ID")]
        public Guid DepartmentId { get; set; } // DepartmentId

        [Required]
        [Display(Name = "Doctor ID")]
        public Guid DoctorId { get; set; } // DoctorId

        [Required]
        [Display(Name = "Patient ID")]
        public Guid PatientId { get; set; } // PatientId

        [Required]
        [Display(Name = "Scheduled start")]
        public DateTimeOffset ScheduledStart { get; set; } // ScheduledStart

        [Required]
        [Display(Name = "Scheduled end")]
        public DateTimeOffset ScheduledEnd { get; set; } // ScheduledEnd

        [Required]
        [Display(Name = "Appointment status ID")]
        public byte AppointmentStatusId { get; set; } // AppointmentStatusId

        [MaxLength(300)]
        [StringLength(300)]
        [Display(Name = "Reason")]
        public string Reason { get; set; } // Reason (length: 300)

        [Required]
        [Display(Name = "Created by user ID")]
        public Guid CreatedByUserId { get; set; } // CreatedByUserId

        [Required]
        [Display(Name = "Created at")]
        public DateTimeOffset CreatedAt { get; set; } // CreatedAt

        [Required]
        [Display(Name = "Updated at")]
        public DateTimeOffset UpdatedAt { get; set; } // UpdatedAt

        [Required]
        [Display(Name = "Is deleted")]
        public bool IsDeleted { get; set; } // IsDeleted

        [Display(Name = "Reminder sent at")]
        public DateTimeOffset? ReminderSentAt { get; set; } // ReminderSentAt

        // Reverse navigation

        /// <summary>
        /// Child AppointmentStatusHistories where [AppointmentStatusHistory].[AppointmentId] point to this entity (FK_AppointmentStatusHistory_Appointment)
        /// </summary>
        public ICollection<AppointmentStatusHistory> AppointmentStatusHistories { get; set; } // AppointmentStatusHistory.FK_AppointmentStatusHistory_Appointment

        /// <summary>
        /// Child MedicalRecords where [MedicalRecords].[AppointmentId] point to this entity (FK_MedicalRecords_Appointment)
        /// </summary>
        public ICollection<MedicalRecord> MedicalRecords { get; set; } // MedicalRecords.FK_MedicalRecords_Appointment

        // Foreign keys

        /// <summary>
        /// Parent AppointmentStatus pointed by [Appointments].([AppointmentStatusId]) (FK_Appointments_Status)
        /// </summary>
        public AppointmentStatus AppointmentStatus { get; set; } // FK_Appointments_Status

        /// <summary>
        /// Parent Clinic pointed by [Appointments].([ClinicId]) (FK_Appointments_Clinic)
        /// </summary>
        public Clinic Clinic { get; set; } // FK_Appointments_Clinic

        /// <summary>
        /// Parent Department pointed by [Appointments].([DepartmentId]) (FK_Appointments_Department)
        /// </summary>
        public Department Department { get; set; } // FK_Appointments_Department

        /// <summary>
        /// Parent Doctor pointed by [Appointments].([DoctorId]) (FK_Appointments_Doctor)
        /// </summary>
        public Doctor Doctor { get; set; } // FK_Appointments_Doctor

        /// <summary>
        /// Parent Patient pointed by [Appointments].([PatientId]) (FK_Appointments_Patient)
        /// </summary>
        public Patient Patient { get; set; } // FK_Appointments_Patient

        /// <summary>
        /// Parent User pointed by [Appointments].([CreatedByUserId]) (FK_Appointments_CreatedBy)
        /// </summary>
        public User User { get; set; } // FK_Appointments_CreatedBy

        public Appointment()
        {
            AppointmentId = Guid.NewGuid();
            AppointmentStatusId = 1;
            CreatedAt = DateTimeOffset.Now;
            UpdatedAt = DateTimeOffset.Now;
            IsDeleted = false;
            AppointmentStatusHistories = new List<AppointmentStatusHistory>();
            MedicalRecords = new List<MedicalRecord>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
