// <auto-generated>
// ReSharper disable All

using HospitalReservationsAPI;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Threading;
using System.Threading.Tasks;

namespace HospitalReservationsAPI
{
    // AppointmentStatusHistory
    [Table("AppointmentStatusHistory", Schema = "dbo")]
    public partial class AppointmentStatusHistory
    {
        [Key, Column(Order = 1)]
        [Required]
        [Display(Name = "History ID")]
        public long HistoryId { get; set; } // HistoryId (Primary key)

        [Required]
        [Display(Name = "Appointment ID")]
        public Guid AppointmentId { get; set; } // AppointmentId

        [Display(Name = "Old status ID")]
        public byte? OldStatusId { get; set; } // OldStatusId

        [Required]
        [Display(Name = "New status ID")]
        public byte NewStatusId { get; set; } // NewStatusId

        [Display(Name = "Changed by user ID")]
        public Guid? ChangedByUserId { get; set; } // ChangedByUserId

        [Required]
        [Display(Name = "Changed at")]
        public DateTimeOffset ChangedAt { get; set; } // ChangedAt

        [MaxLength(300)]
        [StringLength(300)]
        [Display(Name = "Reason")]
        public string Reason { get; set; } // Reason (length: 300)

        // Foreign keys

        /// <summary>
        /// Parent Appointment pointed by [AppointmentStatusHistory].([AppointmentId]) (FK_AppointmentStatusHistory_Appointment)
        /// </summary>
        public Appointment Appointment { get; set; } // FK_AppointmentStatusHistory_Appointment

        /// <summary>
        /// Parent AppointmentStatus pointed by [AppointmentStatusHistory].([NewStatusId]) (FK_AppointmentStatusHistory_NewStatus)
        /// </summary>
        public AppointmentStatus NewStatus { get; set; } // FK_AppointmentStatusHistory_NewStatus

        /// <summary>
        /// Parent AppointmentStatus pointed by [AppointmentStatusHistory].([OldStatusId]) (FK_AppointmentStatusHistory_OldStatus)
        /// </summary>
        public AppointmentStatus OldStatus { get; set; } // FK_AppointmentStatusHistory_OldStatus

        /// <summary>
        /// Parent User pointed by [AppointmentStatusHistory].([ChangedByUserId]) (FK_AppointmentStatusHistory_ChangedBy)
        /// </summary>
        public User User { get; set; } // FK_AppointmentStatusHistory_ChangedBy

        public AppointmentStatusHistory()
        {
            ChangedAt = DateTimeOffset.Now;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
