// <auto-generated>
// ReSharper disable All

using HospitalReservationsAPI;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Threading;
using System.Threading.Tasks;

namespace HospitalReservationsAPI
{
    // AppointmentStatuses
    [Table("AppointmentStatuses", Schema = "dbo")]
    public partial class AppointmentStatus
    {
        [Key, Column(Order = 1)]
        [Required]
        [Display(Name = "Appointment status ID")]
        public byte AppointmentStatusId { get; set; } // AppointmentStatusId (Primary key)

        [MaxLength(30)]
        [StringLength(30)]
        [Required(AllowEmptyStrings = true)]
        [Display(Name = "Code")]
        public string Code { get; set; } // Code (length: 30)

        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Description")]
        public string Description { get; set; } // Description (length: 100)

        // Reverse navigation

        /// <summary>
        /// Child Appointments where [Appointments].[AppointmentStatusId] point to this entity (FK_Appointments_Status)
        /// </summary>
        public ICollection<Appointment> Appointments { get; set; } // Appointments.FK_Appointments_Status

        /// <summary>
        /// Child AppointmentStatusHistories where [AppointmentStatusHistory].[NewStatusId] point to this entity (FK_AppointmentStatusHistory_NewStatus)
        /// </summary>
        public ICollection<AppointmentStatusHistory> AppointmentStatusHistories_NewStatusId { get; set; } // AppointmentStatusHistory.FK_AppointmentStatusHistory_NewStatus

        /// <summary>
        /// Child AppointmentStatusHistories where [AppointmentStatusHistory].[OldStatusId] point to this entity (FK_AppointmentStatusHistory_OldStatus)
        /// </summary>
        public ICollection<AppointmentStatusHistory> AppointmentStatusHistories_OldStatusId { get; set; } // AppointmentStatusHistory.FK_AppointmentStatusHistory_OldStatus

        public AppointmentStatus()
        {
            Appointments = new List<Appointment>();
            AppointmentStatusHistories_NewStatusId = new List<AppointmentStatusHistory>();
            AppointmentStatusHistories_OldStatusId = new List<AppointmentStatusHistory>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
