// <auto-generated>
// ReSharper disable All

using HospitalReservationsAPI;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Threading;
using System.Threading.Tasks;

namespace HospitalReservationsAPI
{
    // AuditLogs
    [Table("AuditLogs", Schema = "audit")]
    public partial class audit_AuditLog
    {
        [Key, Column(Order = 1)]
        [Required]
        [Display(Name = "Audit log ID")]
        public long AuditLogId { get; set; } // AuditLogId (Primary key)

        [Display(Name = "User ID")]
        public Guid? UserId { get; set; } // UserId

        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Role")]
        public string Role { get; set; } // Role (length: 50)

        [Required]
        [Display(Name = "Timestamp")]
        public DateTimeOffset Timestamp { get; set; } // Timestamp

        [MaxLength(50)]
        [StringLength(50)]
        [Required(AllowEmptyStrings = true)]
        [Display(Name = "Action type")]
        public string ActionType { get; set; } // ActionType (length: 50)

        [MaxLength(50)]
        [StringLength(50)]
        [Required(AllowEmptyStrings = true)]
        [Display(Name = "Entity type")]
        public string EntityType { get; set; } // EntityType (length: 50)

        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Entity ID")]
        public string EntityId { get; set; } // EntityId (length: 100)

        [MaxLength(45)]
        [StringLength(45)]
        [Display(Name = "Source ip")]
        public string SourceIp { get; set; } // SourceIp (length: 45)

        [MaxLength(400)]
        [StringLength(400)]
        [Display(Name = "User agent")]
        public string UserAgent { get; set; } // UserAgent (length: 400)

        [Display(Name = "Before snapshot")]
        public string BeforeSnapshot { get; set; } // BeforeSnapshot

        [Display(Name = "After snapshot")]
        public string AfterSnapshot { get; set; } // AfterSnapshot

        public audit_AuditLog()
        {
            Timestamp = DateTimeOffset.Now;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
