// <auto-generated>
// ReSharper disable All

using HospitalReservationsAPI;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Threading;
using System.Threading.Tasks;

namespace HospitalReservationsAPI
{
    // Clinics
    [Table("Clinics", Schema = "dbo")]
    public partial class Clinic
    {
        [Key, Column(Order = 1)]
        [Required]
        [Display(Name = "Clinic ID")]
        public Guid ClinicId { get; set; } // ClinicId (Primary key)

        [MaxLength(200)]
        [StringLength(200)]
        [Required(AllowEmptyStrings = true)]
        [Display(Name = "Name")]
        public string Name { get; set; } // Name (length: 200)

        [MaxLength(300)]
        [StringLength(300)]
        [Display(Name = "Address")]
        public string Address { get; set; } // Address (length: 300)

        [MaxLength(30)]
        [StringLength(30)]
        [Display(Name = "Phone")]
        public string Phone { get; set; } // Phone (length: 30)

        [Required]
        [Display(Name = "Is active")]
        public bool IsActive { get; set; } // IsActive

        [Required]
        [Display(Name = "Is deleted")]
        public bool IsDeleted { get; set; } // IsDeleted

        [Required]
        [Display(Name = "Created at")]
        public DateTimeOffset CreatedAt { get; set; } // CreatedAt

        [Required]
        [Display(Name = "Updated at")]
        public DateTimeOffset UpdatedAt { get; set; } // UpdatedAt

        [Display(Name = "Deleted at")]
        public DateTimeOffset? DeletedAt { get; set; } // DeletedAt

        [Display(Name = "Manager user ID")]
        public Guid? ManagerUserId { get; set; } // ManagerUserId

        /// <summary>
        /// Parent User pointed by [Clinics].([ManagerUserId]) (FK_Clinics_ManagerUser)
        /// </summary>
        public User ManagerUser { get; set; } // FK_Clinics_ManagerUser

        // Reverse navigation

        /// <summary>
        /// Child Appointments where [Appointments].[ClinicId] point to this entity (FK_Appointments_Clinic)
        /// </summary>
        public ICollection<Appointment> Appointments { get; set; } // Appointments.FK_Appointments_Clinic

        /// <summary>
        /// Child Departments where [Departments].[ClinicId] point to this entity (FK_Departments_Clinic)
        /// </summary>
        public ICollection<Department> Departments { get; set; } // Departments.FK_Departments_Clinic

        /// <summary>
        /// Child Doctors where [Doctors].[ClinicId] point to this entity (FK_Doctors_Clinic)
        /// </summary>
        public ICollection<Doctor> Doctors { get; set; } // Doctors.FK_Doctors_Clinic

        /// <summary>
        /// Child DoctorSchedules where [DoctorSchedules].[ClinicId] point to this entity (FK_DoctorSchedules_Clinic)
        /// </summary>
        public ICollection<DoctorSchedule> DoctorSchedules { get; set; } // DoctorSchedules.FK_DoctorSchedules_Clinic

        public Clinic()
        {
            ClinicId = Guid.NewGuid();
            IsActive = true;
            IsDeleted = false;
            CreatedAt = DateTimeOffset.Now;
            UpdatedAt = DateTimeOffset.Now;
            Appointments = new List<Appointment>();
            Departments = new List<Department>();
            Doctors = new List<Doctor>();
            DoctorSchedules = new List<DoctorSchedule>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
