// <auto-generated>
// ReSharper disable All

using HospitalReservationsAPI;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Threading;
using System.Threading.Tasks;

namespace HospitalReservationsAPI
{
    // Departments
    [Table("Departments", Schema = "dbo")]
    public partial class Department
    {
        [Key, Column(Order = 1)]
        [Required]
        [Display(Name = "Department ID")]
        public Guid DepartmentId { get; set; } // DepartmentId (Primary key)

        [Required]
        [Display(Name = "Clinic ID")]
        public Guid ClinicId { get; set; } // ClinicId

        [MaxLength(150)]
        [StringLength(150)]
        [Required(AllowEmptyStrings = true)]
        [Display(Name = "Name")]
        public string Name { get; set; } // Name (length: 150)

        [Required]
        [Display(Name = "Is active")]
        public bool IsActive { get; set; } // IsActive

        [Required]
        [Display(Name = "Created at")]
        public DateTimeOffset CreatedAt { get; set; } // CreatedAt

        // Reverse navigation

        /// <summary>
        /// Child Appointments where [Appointments].[DepartmentId] point to this entity (FK_Appointments_Department)
        /// </summary>
        public ICollection<Appointment> Appointments { get; set; } // Appointments.FK_Appointments_Department

        /// <summary>
        /// Child Doctors where [Doctors].[DepartmentId] point to this entity (FK_Doctors_Department)
        /// </summary>
        public ICollection<Doctor> Doctors { get; set; } // Doctors.FK_Doctors_Department

        // Foreign keys

        /// <summary>
        /// Parent Clinic pointed by [Departments].([ClinicId]) (FK_Departments_Clinic)
        /// </summary>
        public Clinic Clinic { get; set; } // FK_Departments_Clinic

        public Department()
        {
            DepartmentId = Guid.NewGuid();
            IsActive = true;
            CreatedAt = DateTimeOffset.Now;
            Appointments = new List<Appointment>();
            Doctors = new List<Doctor>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
