// <auto-generated>
// ReSharper disable All

using HospitalReservationsAPI;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Threading;
using System.Threading.Tasks;

namespace HospitalReservationsAPI
{
    // DoctorSchedules
    [Table("DoctorSchedules", Schema = "dbo")]
    public partial class DoctorSchedule
    {
        [Key, Column(Order = 1)]
        [Required]
        [Display(Name = "Schedule ID")]
        public Guid ScheduleId { get; set; } // ScheduleId (Primary key)

        [Required]
        [Display(Name = "Doctor ID")]
        public Guid DoctorId { get; set; } // DoctorId

        [Required]
        [Display(Name = "Clinic ID")]
        public Guid ClinicId { get; set; } // ClinicId

        [Required]
        [Display(Name = "Day of week")]
        public byte DayOfWeek { get; set; } // DayOfWeek

        [Required]
        [Display(Name = "Start time")]
        public TimeSpan StartTime { get; set; } // StartTime

        [Required]
        [Display(Name = "End time")]
        public TimeSpan EndTime { get; set; } // EndTime

        [Required]
        [Display(Name = "Slot minutes")]
        public int SlotMinutes { get; set; } // SlotMinutes

        [Required]
        [Display(Name = "Effective from")]
        public DateTime EffectiveFrom { get; set; } // EffectiveFrom

        [Display(Name = "Effective to")]
        public DateTime? EffectiveTo { get; set; } // EffectiveTo

        [Required]
        [Display(Name = "Is active")]
        public bool IsActive { get; set; } // IsActive

        [Required]
        [Display(Name = "Created at")]
        public DateTimeOffset CreatedAt { get; set; } // CreatedAt

        // Foreign keys

        /// <summary>
        /// Parent Clinic pointed by [DoctorSchedules].([ClinicId]) (FK_DoctorSchedules_Clinic)
        /// </summary>
        public Clinic Clinic { get; set; } // FK_DoctorSchedules_Clinic

        /// <summary>
        /// Parent Doctor pointed by [DoctorSchedules].([DoctorId]) (FK_DoctorSchedules_Doctor)
        /// </summary>
        public Doctor Doctor { get; set; } // FK_DoctorSchedules_Doctor

        public DoctorSchedule()
        {
            ScheduleId = Guid.NewGuid();
            SlotMinutes = 15;
            IsActive = true;
            CreatedAt = DateTimeOffset.Now;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
