// <auto-generated>
// ReSharper disable All

using HospitalReservationsAPI;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Threading;
using System.Threading.Tasks;

namespace HospitalReservationsAPI
{
    // Doctors
    [Table("Doctors", Schema = "dbo")]
    public partial class Doctor
    {
        [Key, Column(Order = 1)]
        [Required]
        [Display(Name = "Doctor ID")]
        public Guid DoctorId { get; set; } // DoctorId (Primary key)

        [Required]
        [Display(Name = "User ID")]
        public Guid UserId { get; set; } // UserId

        [Required]
        [Display(Name = "Clinic ID")]
        public Guid ClinicId { get; set; } // ClinicId

        [Required]
        [Display(Name = "Department ID")]
        public Guid DepartmentId { get; set; } // DepartmentId

        [MaxLength(11)]
        [StringLength(11)]
        [Display(Name = "AMKA")]
        public string Amka { get; set; } // AMKA (length: 11)

        [MaxLength(150)]
        [StringLength(150)]
        [Required(AllowEmptyStrings = true)]
        [Display(Name = "Specialty")]
        public string Specialty { get; set; } // Specialty (length: 150)

        [MaxLength(50)]
        [StringLength(50)]
        [Required(AllowEmptyStrings = true)]
        [Display(Name = "License number")]
        public string LicenseNumber { get; set; } // LicenseNumber (length: 50)

        [Required]
        [Display(Name = "Is active")]
        public bool IsActive { get; set; } // IsActive

        [Required]
        [Display(Name = "Is deleted")]
        public bool IsDeleted { get; set; } // IsDeleted

        [Required]
        [Display(Name = "Created at")]
        public DateTimeOffset CreatedAt { get; set; } // CreatedAt

        [Required]
        [Display(Name = "Updated at")]
        public DateTimeOffset UpdatedAt { get; set; } // UpdatedAt

        [Display(Name = "Deleted at")]
        public DateTimeOffset? DeletedAt { get; set; } // DeletedAt

        // Reverse navigation

        /// <summary>
        /// Child Appointments where [Appointments].[DoctorId] point to this entity (FK_Appointments_Doctor)
        /// </summary>
        public ICollection<Appointment> Appointments { get; set; } // Appointments.FK_Appointments_Doctor

        /// <summary>
        /// Child DoctorSchedules where [DoctorSchedules].[DoctorId] point to this entity (FK_DoctorSchedules_Doctor)
        /// </summary>
        public ICollection<DoctorSchedule> DoctorSchedules { get; set; } // DoctorSchedules.FK_DoctorSchedules_Doctor

        /// <summary>
        /// Child MedicalRecords where [MedicalRecords].[DoctorId] point to this entity (FK_MedicalRecords_Doctor)
        /// </summary>
        public ICollection<MedicalRecord> MedicalRecords { get; set; } // MedicalRecords.FK_MedicalRecords_Doctor

        // Foreign keys

        /// <summary>
        /// Parent Clinic pointed by [Doctors].([ClinicId]) (FK_Doctors_Clinic)
        /// </summary>
        public Clinic Clinic { get; set; } // FK_Doctors_Clinic

        /// <summary>
        /// Parent Department pointed by [Doctors].([DepartmentId]) (FK_Doctors_Department)
        /// </summary>
        public Department Department { get; set; } // FK_Doctors_Department

        /// <summary>
        /// Parent User pointed by [Doctors].([UserId]) (FK_Doctors_User)
        /// </summary>
        public User User { get; set; } // FK_Doctors_User

        public Doctor()
        {
            DoctorId = Guid.NewGuid();
            IsActive = true;
            IsDeleted = false;
            CreatedAt = DateTimeOffset.Now;
            UpdatedAt = DateTimeOffset.Now;
            Appointments = new List<Appointment>();
            DoctorSchedules = new List<DoctorSchedule>();
            MedicalRecords = new List<MedicalRecord>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
