// <auto-generated>
// ReSharper disable All

using HospitalReservationsAPI;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Threading;
using System.Threading.Tasks;

namespace HospitalReservationsAPI
{
    // LoginApplicationForms
    [Table("LoginApplicationForms", Schema = "dbo")]
    public partial class LoginApplicationForm
    {
        [Key, Column(Order = 1)]
        [Required]
        [Display(Name = "Id")]
        public long Id { get; set; } // Id (Primary key)

        [Display(Name = "Parent ID")]
        public long? ParentId { get; set; } // ParentId

        [Display(Name = "Name")]
        public string Name { get; set; } // Name

        [Display(Name = "Route element")]
        public string RouteElement { get; set; } // RouteElement

        [Display(Name = "Route comb path")]
        public string RouteCombPath { get; set; } // RouteCombPath

        [Display(Name = "Nav url")]
        public string NavUrl { get; set; } // NavUrl

        [Display(Name = "Nav title")]
        public string NavTitle { get; set; } // NavTitle

        [Display(Name = "Nav icon")]
        public string NavIcon { get; set; } // NavIcon

        [Display(Name = "Nav font icon")]
        public string NavFontIcon { get; set; } // NavFontIcon

        [Display(Name = "Nav has bullet")]
        public bool? NavHasBullet { get; set; } // NavHasBullet

        [Display(Name = "Nav has children")]
        public bool? NavHasChildren { get; set; } // NavHasChildren

        [Display(Name = "Can edit")]
        public bool? CanEdit { get; set; } // CanEdit

        [Display(Name = "Visible")]
        public bool? Visible { get; set; } // Visible

        [Display(Name = "Dev visible")]
        public bool? DevVisible { get; set; } // DevVisible

        [Display(Name = "Order value")]
        public int? OrderValue { get; set; } // OrderValue

        [Display(Name = "Only route")]
        public bool? OnlyRoute { get; set; } // OnlyRoute

        [Display(Name = "Is external link")]
        public bool? IsExternalLink { get; set; } // IsExternalLink

        [Required]
        [Display(Name = "Is for all user")]
        public bool IsForAllUser { get; set; } // IsForAllUser

        // Reverse navigation

        /// <summary>
        /// Child LoginApplicationFormRights where [LoginApplicationFormRights].[ApplicationFormId] point to this entity (FK_LoginApplicationFormRights_LoginApplicationForms)
        /// </summary>
        public ICollection<LoginApplicationFormRight> LoginApplicationFormRights { get; set; } // LoginApplicationFormRights.FK_LoginApplicationFormRights_LoginApplicationForms

        public LoginApplicationForm()
        {
            LoginApplicationFormRights = new List<LoginApplicationFormRight>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
