// <auto-generated>
// ReSharper disable All

using HospitalReservationsAPI;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Threading;
using System.Threading.Tasks;

namespace HospitalReservationsAPI
{
    // LoginApplicationFormRights
    [Table("LoginApplicationFormRights", Schema = "dbo")]
    public partial class LoginApplicationFormRight
    {
        [Key, Column(Order = 1)]
        [Required]
        [Display(Name = "Id")]
        public long Id { get; set; } // Id (Primary key)

        [Required]
        [Display(Name = "Application form ID")]
        public long ApplicationFormId { get; set; } // ApplicationFormId

        [Required]
        [Display(Name = "Role ID")]
        public int RoleId { get; set; } // RoleId

        [Display(Name = "Can edit")]
        public bool? CanEdit { get; set; } // CanEdit

        // Foreign keys

        /// <summary>
        /// Parent Role pointed by [LoginApplicationFormRights].([RoleId]) (FK_LoginApplicationFormRights_Roles)
        /// </summary>
        public Role Role { get; set; } // FK_LoginApplicationFormRights_Roles

        /// <summary>
        /// Parent LoginApplicationForm pointed by [LoginApplicationFormRights].([ApplicationFormId]) (FK_LoginApplicationFormRights_LoginApplicationForms)
        /// </summary>
        public LoginApplicationForm LoginApplicationForm { get; set; } // FK_LoginApplicationFormRights_LoginApplicationForms

        public LoginApplicationFormRight()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
