// <auto-generated>
// ReSharper disable All

using HospitalReservationsAPI;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Threading;
using System.Threading.Tasks;

namespace HospitalReservationsAPI
{
    // MedicalRecords
    [Table("MedicalRecords", Schema = "dbo")]
    public partial class MedicalRecord
    {
        [Key, Column(Order = 1)]
        [Required]
        [Display(Name = "Record ID")]
        public Guid RecordId { get; set; } // RecordId (Primary key)

        [Required]
        [Display(Name = "Patient ID")]
        public Guid PatientId { get; set; } // PatientId

        [Display(Name = "Appointment ID")]
        public Guid? AppointmentId { get; set; } // AppointmentId

        [Required]
        [Display(Name = "Doctor ID")]
        public Guid DoctorId { get; set; } // DoctorId

        [Required(AllowEmptyStrings = true)]
        [Display(Name = "Notes")]
        public string Notes { get; set; } // Notes

        [Required]
        [Display(Name = "Is deleted")]
        public bool IsDeleted { get; set; } // IsDeleted

        [Required]
        [Display(Name = "Created at")]
        public DateTimeOffset CreatedAt { get; set; } // CreatedAt

        [Required]
        [Display(Name = "Updated at")]
        public DateTimeOffset UpdatedAt { get; set; } // UpdatedAt

        [Display(Name = "Deleted at")]
        public DateTimeOffset? DeletedAt { get; set; } // DeletedAt

        // Foreign keys

        /// <summary>
        /// Parent Appointment pointed by [MedicalRecords].([AppointmentId]) (FK_MedicalRecords_Appointment)
        /// </summary>
        public Appointment Appointment { get; set; } // FK_MedicalRecords_Appointment

        /// <summary>
        /// Parent Doctor pointed by [MedicalRecords].([DoctorId]) (FK_MedicalRecords_Doctor)
        /// </summary>
        public Doctor Doctor { get; set; } // FK_MedicalRecords_Doctor

        /// <summary>
        /// Parent Patient pointed by [MedicalRecords].([PatientId]) (FK_MedicalRecords_Patient)
        /// </summary>
        public Patient Patient { get; set; } // FK_MedicalRecords_Patient

        public MedicalRecord()
        {
            RecordId = Guid.NewGuid();
            IsDeleted = false;
            CreatedAt = DateTimeOffset.Now;
            UpdatedAt = DateTimeOffset.Now;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
