// <auto-generated>
// ReSharper disable All

using HospitalReservationsAPI;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Threading;
using System.Threading.Tasks;

namespace HospitalReservationsAPI
{
    // Notifications
    [Table("Notifications", Schema = "dbo")]
    public partial class Notification
    {
        [Key, Column(Order = 1)]
        [Required]
        [Display(Name = "Notification ID")]
        public Guid NotificationId { get; set; } // NotificationId (Primary key)

        [Required]
        [Display(Name = "User ID")]
        public Guid UserId { get; set; } // UserId

        [MaxLength(50)]
        [StringLength(50)]
        [Required(AllowEmptyStrings = true)]
        [Display(Name = "Type")]
        public string Type { get; set; } // Type (length: 50)

        [Display(Name = "Payload")]
        public string Payload { get; set; } // Payload

        [Required]
        [Display(Name = "Is read")]
        public bool IsRead { get; set; } // IsRead

        [Required]
        [Display(Name = "Created at")]
        public DateTimeOffset CreatedAt { get; set; } // CreatedAt

        [Display(Name = "Read at")]
        public DateTimeOffset? ReadAt { get; set; } // ReadAt

        // Foreign keys

        /// <summary>
        /// Parent User pointed by [Notifications].([UserId]) (FK_Notifications_User)
        /// </summary>
        public User User { get; set; } // FK_Notifications_User

        public Notification()
        {
            NotificationId = Guid.NewGuid();
            IsRead = false;
            CreatedAt = DateTimeOffset.Now;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
