// <auto-generated>
// ReSharper disable All

using HospitalReservationsAPI;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Threading;
using System.Threading.Tasks;

namespace HospitalReservationsAPI
{
    // Patients
    [Table("Patients", Schema = "dbo")]
    public partial class Patient
    {
        [Key, Column(Order = 1)]
        [Required]
        [Display(Name = "Patient ID")]
        public Guid PatientId { get; set; } // PatientId (Primary key)

        [Display(Name = "User ID")]
        public Guid? UserId { get; set; } // UserId

        [MaxLength(100)]
        [StringLength(100)]
        [Required(AllowEmptyStrings = true)]
        [Display(Name = "First name")]
        public string FirstName { get; set; } // FirstName (length: 100)

        [MaxLength(100)]
        [StringLength(100)]
        [Required(AllowEmptyStrings = true)]
        [Display(Name = "Last name")]
        public string LastName { get; set; } // LastName (length: 100)

        [MaxLength(11)]
        [StringLength(11)]
        [Display(Name = "Amka")]
        public string Amka { get; set; } // AMKA (length: 11)

        [Required]
        [Display(Name = "Date of birth")]
        public DateTime DateOfBirth { get; set; } // DateOfBirth

        [MaxLength(30)]
        [StringLength(30)]
        [Display(Name = "Phone")]
        public string Phone { get; set; } // Phone (length: 30)

        [MaxLength(256)]
        [StringLength(256)]
        [Display(Name = "Email")]
        public string Email { get; set; } // Email (length: 256)

        [Required]
        [Display(Name = "Is deleted")]
        public bool IsDeleted { get; set; } // IsDeleted

        [Required]
        [Display(Name = "Created at")]
        public DateTimeOffset CreatedAt { get; set; } // CreatedAt

        [Required]
        [Display(Name = "Updated at")]
        public DateTimeOffset UpdatedAt { get; set; } // UpdatedAt

        [Display(Name = "Deleted at")]
        public DateTimeOffset? DeletedAt { get; set; } // DeletedAt

        // Reverse navigation

        /// <summary>
        /// Child Appointments where [Appointments].[PatientId] point to this entity (FK_Appointments_Patient)
        /// </summary>
        public ICollection<Appointment> Appointments { get; set; } // Appointments.FK_Appointments_Patient

        /// <summary>
        /// Child MedicalRecords where [MedicalRecords].[PatientId] point to this entity (FK_MedicalRecords_Patient)
        /// </summary>
        public ICollection<MedicalRecord> MedicalRecords { get; set; } // MedicalRecords.FK_MedicalRecords_Patient

        // Foreign keys

        /// <summary>
        /// Parent User pointed by [Patients].([UserId]) (FK_Patients_User)
        /// </summary>
        public User User { get; set; } // FK_Patients_User

        public Patient()
        {
            PatientId = Guid.NewGuid();
            IsDeleted = false;
            CreatedAt = DateTimeOffset.Now;
            UpdatedAt = DateTimeOffset.Now;
            Appointments = new List<Appointment>();
            MedicalRecords = new List<MedicalRecord>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
