// <auto-generated>
// ReSharper disable All

using HospitalReservationsAPI;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Threading;
using System.Threading.Tasks;

namespace HospitalReservationsAPI
{
    // Permissions
    [Table("Permissions", Schema = "dbo")]
    public partial class Permission
    {
        [Key, Column(Order = 1)]
        [Required]
        [Display(Name = "Permission ID")]
        public int PermissionId { get; set; } // PermissionId (Primary key)

        [MaxLength(100)]
        [StringLength(100)]
        [Required(AllowEmptyStrings = true)]
        [Display(Name = "Name")]
        public string Name { get; set; } // Name (length: 100)

        [MaxLength(200)]
        [StringLength(200)]
        [Display(Name = "Description")]
        public string Description { get; set; } // Description (length: 200)

        // Reverse navigation

        /// <summary>
        /// Child RolePermissions where [RolePermissions].[PermissionId] point to this entity (FK_RolePermissions_Permission)
        /// </summary>
        public ICollection<RolePermission> RolePermissions { get; set; } // RolePermissions.FK_RolePermissions_Permission

        public Permission()
        {
            RolePermissions = new List<RolePermission>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
