// <auto-generated>
// ReSharper disable All

using HospitalReservationsAPI;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Threading;
using System.Threading.Tasks;

namespace HospitalReservationsAPI
{
    // Roles
    [Table("Roles", Schema = "dbo")]
    public partial class Role
    {
        [Key, Column(Order = 1)]
        [Required]
        [Display(Name = "Role ID")]
        public int RoleId { get; set; } // RoleId (Primary key)

        [MaxLength(50)]
        [StringLength(50)]
        [Required(AllowEmptyStrings = true)]
        [Display(Name = "Name")]
        public string Name { get; set; } // Name (length: 50)

        [MaxLength(200)]
        [StringLength(200)]
        [Display(Name = "Description")]
        public string Description { get; set; } // Description (length: 200)

        [Required]
        [Display(Name = "Created at")]
        public DateTimeOffset CreatedAt { get; set; } // CreatedAt

        // Reverse navigation

        /// <summary>
        /// Child RolePermissions where [RolePermissions].[RoleId] point to this entity (FK_RolePermissions_Role)
        /// </summary>
        public ICollection<RolePermission> RolePermissions { get; set; } // RolePermissions.FK_RolePermissions_Role

        /// <summary>
        /// Child UserRoles where [UserRoles].[RoleId] point to this entity (FK_UserRoles_Role)
        /// </summary>
        public ICollection<UserRole> UserRoles { get; set; } // UserRoles.FK_UserRoles_Role

        public Role()
        {
            CreatedAt = DateTimeOffset.Now;
            RolePermissions = new List<RolePermission>();
            UserRoles = new List<UserRole>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
