// <auto-generated>
// ReSharper disable All

using HospitalReservationsAPI;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Threading;
using System.Threading.Tasks;

namespace HospitalReservationsAPI
{
    // RolePermissions
    [Table("RolePermissions", Schema = "dbo")]
    public partial class RolePermission
    {
        [Key, Column(Order = 1)]
        [Required]
        [Display(Name = "Role ID")]
        public int RoleId { get; set; } // RoleId (Primary key)

        [Key, Column(Order = 2)]
        [Required]
        [Display(Name = "Permission ID")]
        public int PermissionId { get; set; } // PermissionId (Primary key)

        // Foreign keys

        /// <summary>
        /// Parent Permission pointed by [RolePermissions].([PermissionId]) (FK_RolePermissions_Permission)
        /// </summary>
        public Permission Permission { get; set; } // FK_RolePermissions_Permission

        /// <summary>
        /// Parent Role pointed by [RolePermissions].([RoleId]) (FK_RolePermissions_Role)
        /// </summary>
        public Role Role { get; set; } // FK_RolePermissions_Role

        public RolePermission()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
