// <auto-generated>
// ReSharper disable All

using HospitalReservationsAPI;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Threading;
using System.Threading.Tasks;

namespace HospitalReservationsAPI
{
    // UserRoles
    [Table("UserRoles", Schema = "dbo")]
    public partial class UserRole
    {
        [Key, Column(Order = 1)]
        [Required]
        [Display(Name = "User ID")]
        public Guid UserId { get; set; } // UserId (Primary key)

        [Key, Column(Order = 2)]
        [Required]
        [Display(Name = "Role ID")]
        public int RoleId { get; set; } // RoleId (Primary key)

        [Required]
        [Display(Name = "Assigned at")]
        public DateTimeOffset AssignedAt { get; set; } // AssignedAt

        [Display(Name = "Assigned by user ID")]
        public Guid? AssignedByUserId { get; set; } // AssignedByUserId

        // Foreign keys

        /// <summary>
        /// Parent Role pointed by [UserRoles].([RoleId]) (FK_UserRoles_Role)
        /// </summary>
        public Role Role { get; set; } // FK_UserRoles_Role

        /// <summary>
        /// Parent User pointed by [UserRoles].([AssignedByUserId]) (FK_UserRoles_AssignedBy)
        /// </summary>
        public User AssignedByUser { get; set; } // FK_UserRoles_AssignedBy

        /// <summary>
        /// Parent User pointed by [UserRoles].([UserId]) (FK_UserRoles_User)
        /// </summary>
        public User User_UserId { get; set; } // FK_UserRoles_User

        public UserRole()
        {
            AssignedAt = DateTimeOffset.Now;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
