// <auto-generated>
// ReSharper disable All

using HospitalReservationsAPI;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Threading;
using System.Threading.Tasks;

namespace HospitalReservationsAPI
{
    // Users
    [Table("Users", Schema = "dbo")]
    public partial class User
    {
        [Key, Column(Order = 1)]
        [Required]
        [Display(Name = "User ID")]
        public Guid UserId { get; set; } // UserId (Primary key)

        [MaxLength(256)]
        [StringLength(256)]
        [Required(AllowEmptyStrings = true)]
        [Display(Name = "Email")]
        public string Email { get; set; } // Email (length: 256)

        [MaxLength(200)]
        [StringLength(200)]
        [Required(AllowEmptyStrings = true)]
        [Display(Name = "Full name")]
        public string FullName { get; set; } // FullName (length: 200)

        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "External provider")]
        public string ExternalProvider { get; set; } // ExternalProvider (length: 50)

        [MaxLength(200)]
        [StringLength(200)]
        [Display(Name = "External subject ID")]
        public string ExternalSubjectId { get; set; } // ExternalSubjectId (length: 200)

        [Required]
        [Display(Name = "Is active")]
        public bool IsActive { get; set; } // IsActive

        [Required]
        [Display(Name = "Is deleted")]
        public bool IsDeleted { get; set; } // IsDeleted

        [Required]
        [Display(Name = "Created at")]
        public DateTimeOffset CreatedAt { get; set; } // CreatedAt

        [Required]
        [Display(Name = "Updated at")]
        public DateTimeOffset UpdatedAt { get; set; } // UpdatedAt

        [Display(Name = "Deleted at")]
        public DateTimeOffset? DeletedAt { get; set; } // DeletedAt

        // Reverse navigation

        /// <summary>
        /// Parent (One-to-One) User pointed by [Doctors].[UserId] (FK_Doctors_User)
        /// </summary>
        public Doctor Doctor { get; set; } // Doctors.FK_Doctors_User

        /// <summary>
        /// Child Appointments where [Appointments].[CreatedByUserId] point to this entity (FK_Appointments_CreatedBy)
        /// </summary>
        public ICollection<Appointment> Appointments { get; set; } // Appointments.FK_Appointments_CreatedBy

        /// <summary>
        /// Child AppointmentStatusHistories where [AppointmentStatusHistory].[ChangedByUserId] point to this entity (FK_AppointmentStatusHistory_ChangedBy)
        /// </summary>
        public ICollection<AppointmentStatusHistory> AppointmentStatusHistories { get; set; } // AppointmentStatusHistory.FK_AppointmentStatusHistory_ChangedBy

        /// <summary>
        /// Child Notifications where [Notifications].[UserId] point to this entity (FK_Notifications_User)
        /// </summary>
        public ICollection<Notification> Notifications { get; set; } // Notifications.FK_Notifications_User

        /// <summary>
        /// Child UserRoles where [UserRoles].[AssignedByUserId] point to this entity (FK_UserRoles_AssignedBy)
        /// </summary>
        public ICollection<UserRole> UserRoles_AssignedByUserId { get; set; } // UserRoles.FK_UserRoles_AssignedBy

        /// <summary>
        /// Child UserRoles where [UserRoles].[UserId] point to this entity (FK_UserRoles_User)
        /// </summary>
        public ICollection<UserRole> UserRoles_UserId { get; set; } // UserRoles.FK_UserRoles_User

        /// <summary>
        /// Parent (One-to-One) User pointed by [Patients].[UserId] (FK_Patients_User)
        /// </summary>
        public Patient Patient { get; set; } // Patients.FK_Patients_User

        public User()
        {
            UserId = Guid.NewGuid();
            IsActive = true;
            IsDeleted = false;
            CreatedAt = DateTimeOffset.Now;
            UpdatedAt = DateTimeOffset.Now;
            Appointments = new List<Appointment>();
            AppointmentStatusHistories = new List<AppointmentStatusHistory>();
            Notifications = new List<Notification>();
            UserRoles_AssignedByUserId = new List<UserRole>();
            UserRoles_UserId = new List<UserRole>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
